/*
 *   Copyright 2014 CapitalOne, LLC.
 *   Further development Copyright 2022 Sapient Corporation.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.publicissapient.kpidashboard.apis.recommendations.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.publicissapient.kpidashboard.apis.model.ServiceResponse;
import com.publicissapient.kpidashboard.apis.recommendations.dto.RecommendationResponseDTO;
import com.publicissapient.kpidashboard.apis.recommendations.service.RecommendationService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.constraints.NotBlank;
import lombok.RequiredArgsConstructor;

/**
 * REST Controller for serving batch-calculated project recommendations.
 */
@Validated
@RestController
@RequestMapping("/v1/recommendations")
@RequiredArgsConstructor
@Tag(name = "Recommendations API v1", description = "APIs for retrieving AI-generated project recommendations from batch calculations")
public class RecommendationController {

	private final RecommendationService recommendationService;

	@Operation(summary = "Get project recommendations by organizational level", description = "Retrieves batch-calculated AI recommendations for projects at the specified organizational hierarchy level. "
			+ "The recommendations are generated by the ai-data-processor batch job and served from pre-calculated data. "
			+ "Response includes project-level recommendations with AI-generated action plans, severity ratings, and metadata about the analysis.", operationId = "getProjectRecommendations")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "Project recommendations retrieved successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = RecommendationResponseDTO.class))),
			@ApiResponse(responseCode = "400", description = "Bad Request - Invalid levelName parameter"),
			@ApiResponse(responseCode = "403", description = "Forbidden - User doesn't have access to the requested data"),
			@ApiResponse(responseCode = "404", description = "Not Found - Hierarchy level not found for the specified levelName"),
			@ApiResponse(responseCode = "500", description = "Internal Server Error - Unexpected error occurred during recommendation retrieval") })
	@GetMapping({ "", "/" })
	public ResponseEntity<ServiceResponse> getRecommendations(
			@Parameter(name = "levelName", description = "The organizational hierarchy level name for which to retrieve recommendations. "
					+ "Must correspond to a valid hierarchy level name (not ID).", required = true, example = "project") @RequestParam @NotBlank(message = "The level name is required") String levelName) {

		return ResponseEntity.ok(recommendationService.getRecommendationsForLevel(levelName));
	}
}